### PR TITLE
Pull l0ner/master into upstream.

### PR DESCRIPTION
**Pull request by l0ner**
See https://github.com/thewtex/tmux-mem-cpu-load/pull/12 for changelist

Credits:
- BSD port: Justin Crawford (https://github.com/Justasic)
- Sysinfo() usage on linux: secularbird (see https://github.com/secularbird/tmux-mem-cpu-load/commit/880f8b196749ad2ed0ed376db0ba4da0595eeead). I've used his idea.

There shouldn't be any merge conflicts. Merge commits are still there (on my branch mergers and upstream pulls) and we should leave them there. Rebasing ensures mess and PITA.

### CODE REVIEW

**Comment by thewtex** [comment]
Please see the comments on the individual commits.

Great to see the code re-organization and the addition of BSD support!

Please help keep the original style and keep the style consistent.

The argument parser copied in can't be used because it is GPL.  The Linux sysinfo sounds good, but it is not current getting the correct output.

All the Boost stuff should be removed.

Please add yourself to the list of contributors in the README.

At some point, it would be great to have the option to use the spark graphs.

**Comment by l0ner** [comment]
Ok, I'm going through the comments and I'm correcting the stuff. Am I allowed to use vim modelines?

**Comment by thewtex** [comment]
vim modelines would be great.

**Comment by l0ner** [comment]
Great, will add them then.

**Comment by l0ner** [comment]
And this should be everything.

### Corrections

- [x] Code style: use Allman-like indentation style, with 2 spaces for each indentation step
- [x] consistent use of lower-case in CMake files
- [x] no boost
- [x] std::string in graph functions instead of char[]
- [x] prefixed version variables
- [x] replaced argument parser with getopt_long based one (way less code and no license conflicts)
- [x] restored /proc/meminfo parsing as method of getting RAM usage.
- [x] removed conflict indicators in README
- [x] better c++11 detection in CMake

### New stuff

- [x] vim mode-lines
- [x] byte unit conversion function used instead of hard-coded divisions
- [x] test case for graph_lines = 0
- [x] CONTRIBUTING file explaining how to contribute and which are the code style guidelines
- [x] AUTHORS file listing all contributors
- [x] Consistent LICENSE headers across all files.

### Stuff to do

- [ ] OpenBSD port merge - I've worked a little bit on this, and nearly finished. I need to do last check-ups and see if the methods used on OpenBSD will work under FreeBSD and OS X. If they do I'll merge those 3 platforms ports into one. But this is stuff for another merge request.

### Note

Since the changes are significant the version major number should be incremented. But this is your decision what version this should be.

**Comment by thewtex** [comment]
Thank you!

I agree this is worthy of a 3.0 release.  I'll merge, test, and release tonight.

**Comment by l0ner** [comment]
Great! :)

**Pull request merged**
