### PR TITLE
Cpu mode

### PR DESCRIPTION
**Pull request by jodavies**
Added a second CPU percentage mode, where we multiply the percentage by the number of cpu threads.

### CODE REVIEW

**Comment by thewtex** [comment]
Thanks for the contribution.

Please update the help output in the README.

**Comment by thewtex** [comment]
Please update the help output in the README and add yourself to the list of contributors.

**Comment by jodavies** [comment]
What else needs to go in the readme? I have put the output as it appears in --help here https://github.com/thewtex/tmux-mem-cpu-load/pull/40/files#diff-88b99bb28683bd5b7e3a204826ead112R129

**Comment by thewtex** [comment]
@jodavies ah I see --help the addition in that diff.  Please add yourself to the list of contributors in the README.

**Pull request merged**
