### PR TITLE
OpenBSD port

### PR DESCRIPTION
**Pull request by l0ner**
## Changes

* OpenBSD port
  * Renamed bsd folder to freebsd since it now contains only files related to FreeBSD
* Update README with supported platforms
* Added notice to CONTRIBUTING about script that can be used to easily strip whitespaces.

Since we are introducing a new platform it may be a good idea to bump up the version minor number.

### CODE REVIEW

**Comment by thewtex** [comment]
Cool! Will review over the next few days.

**Comment by thewtex** [comment]
I tried building this, and there is a is a build error: openbsd/memory.cc:28:21 fatal error: ../luts.h: No such files or directory.

**Comment by l0ner** [comment]
Should be fixed now. I can't test it until tomorrow though.

**Comment by l0ner** [comment]
Now it compiles. I've tested it both on Free and Open BSD and everything is fine.

**Comment by thewtex** [comment]
Better, but it still fails for me on OpenBSD 5.6 with GCC 4.9:

  http://pastebin.calculate-linux.org/en/show/10444

**Comment by l0ner** [comment]
O_o

This is independent from the codebase. Error is about sys/ucred.h (which is not even used in our code). Looks like a problem with the OpenBSD sys libraries, thus, probably an OpenBSD problem.

I'm gonna examine this later on fresh OpenBSD install.

**Comment by l0ner** [comment]
Ok, So I have examined this problem and it truly is a problem with OpenBSD sys source headers. I've tried it on OpenBSD 5.7 and it compiles, but on OpenBSD 5.6 (which is the latest stable release) it fails. All of this is because the sys/ucred.h is missing include to sys/syslimits.h. It seems they have fixed it in their code (see: http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/sys/sys/ucred.h?r1=1.10). 

Now I need to find how to actually update those headers in the system.

**Comment by thewtex** [comment]
Thanks for the detective work.

Since this is already fixed in upstream, can we work around the issues in OpenBSD 5.6 with

#include "sys/syslimits.h"
#include "sys/ucred.h"

?

**Comment by l0ner** [comment]
Actually, Yes. See my last commit for details. Now it should build both on 5.7 and 5.6.

I wish Travis supported OpenBSD and at least last its 2-3 versions.

**Comment by thewtex** [comment]
It builds now :-).

Can the experimental CMake warning be removed?

When running the tests, I get

  sysctl: error getting cpu stats

Did you experience this?

**Comment by l0ner** [comment]
No, I'm not and this should not be happening. It means that we cant get the cpu usage stats and this the cpu meter may be off/not working.

I'm gonna remove warnings and poke a little bit around the CPU meter to see what's happening.

**Comment by l0ner** [comment]
Could you try to compile and run this:

https://gist.github.com/l0ner/c0e3f01bbb26aa88ec71

Also: try to recompile the app, now that I've changed error messages a little bit and check on which sysctl it fails, initial or updated.

**Comment by thewtex** [comment]
The Gist compiles fine.  When it runs, it generates

  sysctl: error getting cpu stats: 12


The CMake configuration message looks better, but the tests still fail.

**Comment by l0ner** [comment]
Ok, this is strange.

Error code 12 means that sysctl cannot store the cpu stats in the provided array, because it's size we provide is too small. This mean that either what sizeof reports is wrong, or on your system there are more  cpu states than user, nice, sys, intr and idle.

What cpu do you have there?

And what command `sysclt kern.cp_time` outputs?

I'll look at cmake test after I resolved this thing.

**Comment by l0ner** [comment]
Try it now.

**Comment by thewtex** [comment]
This is running in a VirtualBox VM with 2 cpu cores.

# sysctl kern.cp_time
kern.cp_time=41,0,205,52,20869

The current build yields:

sysctl: error getting initial cpu stats: Cannot allocate memory

**Comment by l0ner** [comment]
Ok, this is really strange. It should work and I don't know why it isn't. The error you are getting is:

    [ENOMEM]
    The length pointed to by oldlenp is too short to hold the requested value.

(taken directly from OpenBSD sysctl(3) man page. This behaviour is really strange, since we are getting the length through the sizeof() operator, which should report the size of array in which we store cp stats. This is how conky does it on OpenBSD, and I honestly don't know why it doesn't work for you. This most likely indicates some problems with the system and/or memory.

Anyway try compiling and runnign this and posting it's output:
https://gist.github.com/l0ner/c0e3f01bbb26aa88ec71

This will try to guess what's the correct array size on your system and fail if it becomes too big (read comments).

Also give me the output of:
 - `sysctl | grep ncpu`
 - `uname -a`
 - `sysctl hw.usermem`

Is there any way you can give me direct access to your vm. Preferably upload it somwhere so I can download it and try to run it by myself?

**Comment by l0ner** [comment]
Bump?

**Comment by thewtex** [comment]
Sorry for the late follow-up.  I'll get to this tonight.

**Comment by thewtex** [comment]
Or tomorrow night ;-).

**Comment by thewtex** [comment]
Another delay due to some hardware issues.  I will try again tomorrow.

**Comment by thewtex** [comment]
The output of https://gist.github.com/l0ner/c0e3f01bbb26aa88ec71 is:

  Load array size: 20
  Load array size give by sizeof()20
  u_int32_t size: 4
  21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40
  Guessed correct array size: 40
  systcl: error getting cpu stats: 45

sysctl | grep ncpu:

  hw.ncpu=2
  hw.ncpufound=2

uname -a

  OpenBSD openbsd.nc.rr.com 5.6 GENERIC.MP#333 amd64

sysctl hw.usermem

  251576320

**Comment by thewtex** [comment]
Here is the VirtualBox VM I am using:

  https://drive.google.com/file/d/0BzutorxJ0_hCNm9zN0daMnJ6ZE0/view?usp=sharing

The username / password is "matt" / "tmux-mem-cpu-load"

**Comment by l0ner** [comment]
Ok, I've found where lies the problem. On 32bit system (i383) KERN_CPTIME sysctl return values as 32bit uints. On 64bit systems these values get returned as 64bit uints. Testing for architecture should resolve this problem.

Should be fixed with last commit.

I wonder if this will affect FreeBSD too. I'm gonna check it.

**Comment by thewtex** [comment]
Verified!  Woot!

Let me know if there are changes required for FreeBSD. Otherwise, we'll tag 3.1.0.

**Comment by l0ner** [comment]
There are. See #17

**Pull request merged**
