### PR TITLE
Merge l0ner branch.

### PR DESCRIPTION
**Pull request by l0ner**
I've made a lot of changes to tmux-mem-cpu-load. It would be nice to see them in the main codebase.

Changes list:
- Split the whole thing into multiple files. This one is maybe the most important one, since it improves code readability. Not only it's easier to read small files, its less confusing to have platform-specific code in separate files than to have big blocks of code wrapped in #ifdefs. Second thing it will be easier this way to introduce new meters (swap, battery, single cores?).
- Pulled FreeBSD port from Justin Crawford. It's a good code, althoug it needed a little bit of adjusting.
- cpu_graph can be set to 0. In this case the cpu usage graph won't be displayed.
- Linux: instead of parsing files for load averages and memory usage use sysinfo() function the linux kernel provides. This way we'll avoid eventual problems arising from different structures of /proc/meminfo file across differen kernel versions/configs.
- New argument parsing: having 2 positional arguments is not exactly the best idea. What if user wants to specify graph lines count but not the interval? Besides: I'm plannig to introduce output customization in the future, and having argument parsing structured the way it is here will help.

Credits for BSD port should go to Justin Crawford (https://github.com/Justasic)

### CODE REVIEW

**Comment by thewtex** [comment]
Sounds like great changes! I'll review over the next week.

**Comment by thewtex** [comment]
Please rebase on master and remove all merge commits.  According to github, there are merge conflicts with master.

**Comment by l0ner** [comment]
Oh, yeah. Did this already on my master. Should I create new pull request for my master?

**Comment by l0ner** [comment]
Merged upstream to by l0ner branch. Now my master and l0ner branch contain the same code. You can pull changes from any.

**Comment by l0ner** [comment]
Rebased on your master. This wasn't a good idea, since now I see doubled commits in the log. Chaos everywhere.

I'm gonna close this merge request, and open another one on my master, where instead of rebasing I've merged upstream. Less chaos.

**Comment by thewtex** [comment]
:+1: Sounds good.

**Pull request closed without merging**
