### PR TITLE
Also run an OSX Travis build.

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Comment by l0ner** [comment]
+1

**Comment by thewtex** [comment]
According to 

 http://yaml.travis-ci.org/

This repository does not have the required feature flag.  I noticed we didn't get them in the build matrix either. I've sent an email as instructed here:

  http://docs.travis-ci.com/user/multi-os/

**Comment by l0ner** [comment]
We'll wait then.

**Comment by thewtex** [comment]
They replied and said the feature has been turned on -- let's see!

**Pull request merged**
